name: clip
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  screen_recorder: 0.2.0

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.2.16

flutter_native_splash: # スプラッシュ画面
  image: "assets/images/splash.png"
  color: "#121212"
  fullscreen: true
  android_12:
    color: "#121212"
    image: 'assets/images/splash_android12.png'

dev_dependencies:
  flutter_test:
    sdk: flutter






flutter:
  uses-material-design: true
  assets:
  - assets/images/
