name: clip
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.2.16

flutter_native_splash: # スプラッシュ画面
  image: "assets/images/splash.png"
  color: "#121212"
  fullscreen: true
  android_12:
    color: "#121212"
    image: 'assets/images/splash_android12.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.11.0" #icon




flutter_icons: # 初期アイコンの変更
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
